import { Outfit } from "next/font/google";
import "./globals.css";

//components
import Navbar from "./components/Navbar";

const outfit = Outfit({ weight: ["700"], subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
